### ISSUE TITLE
`toSqlKey` with a different column as Id gives an error

### ISSUE THREAD

**Issue by dariooddenino** [parsonsmatt/persistent-typed-db#2]
Hi,

I have a model like this:
```haskell
Foo
  Id sql=other_id
  other_id Int
```
If I run:

```haskell
getFoo :: Int64 -> Handler (Maybe Foo)
getFoo id = runDb $ get $ toSqlKey id
```
I get this error:
```
No instance for (ToBackendKey (SqlFor FooDB) Foo) arising from a use of `getFoo`
```

It runs fine when i use standard id columns.

**Comment by parsonsmatt** [comment]
That's interesting, thanks for reporting. Can you post the output of the following REPL commands?

```haskell
:i FooId
:t FooKey
```

Also, can you verify you're using `Database.Persist.Typed.toSqlKey` instead of `Database.Persist.Sql.toSqlKey`?

**Comment by dariooddenino** [comment]
Yes, I'm using `Database.Persist.Typed.toSqlKey`.

`:i FooId`:
```
data instance EntityField Foo typ where
  FooId :: typ
                                  ~ FooId =>
                                  EntityField Foo typ
``` 

`:t FooKey`:
```
FooKey
  :: Int -> Key Foo

```

**Comment by dariooddenino** [comment]
I had a `Primary other_id` line in my model definition.
Removing it solved the issue. Not sure if it was not supposed to be there or just that the bug is there :D

**Comment by parsonsmatt** [comment]
OK, I think that the `Primary` thing is just going to bork that :\ I'd have to dig into the code generation more. The combination of the `Id` field and the `Primary` might have a weird interaction; `Primary` is usually used to give a different type of ID than normal, or a composite key.

**Comment by dsh** [comment]
I also just ran into this, also with a table I had to use a different `Primary`. 

This might at least warrant documentation of the issue.

**Comment by parsonsmatt** [comment]
I bet I can get an informative type error with an overlappable instance... hmm

**Comment by dsh** [comment]
The original error as reported is informative enough to correct it.

Here is my simplified fix:

```haskell
MyTable 
    myId Int
    Primary myId
  
instance ToBackendKey (SqlFor MyDb) MyTable where
     toBackendKey = SqlForKey . SqlBackendKey . fromIntegral . unMyTableKey
     fromBackendKey = MyTableKey . fromIntegral . unSqlBackendKey . unSqlForKey
```
`fromIntegral` is because `myId` is `Int` and MySQL wants `Int64`.

I haven't tackled this yet for non-int or composite keys, but I will need to and add on what I learn.

This is documented upstream at http://hackage.haskell.org/package/persistent-2.8.2/docs/Database-Persist-Class.html

>>> A `Key` that instead uses a custom type will not be an instance of `ToBackendKey`.
